// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/provider/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/provider/repository.go -destination=internal/domain/provider/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGithubRepo is a mock of GithubRepo interface.
type MockGithubRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGithubRepoMockRecorder
	isgomock struct{}
}

// MockGithubRepoMockRecorder is the mock recorder for MockGithubRepo.
type MockGithubRepoMockRecorder struct {
	mock *MockGithubRepo
}

// NewMockGithubRepo creates a new mock instance.
func NewMockGithubRepo(ctrl *gomock.Controller) *MockGithubRepo {
	mock := &MockGithubRepo{ctrl: ctrl}
	mock.recorder = &MockGithubRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubRepo) EXPECT() *MockGithubRepoMockRecorder {
	return m.recorder
}

// AddCollaborator mocks base method.
func (m *MockGithubRepo) AddCollaborator(ctx context.Context, repo, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollaborator", ctx, repo, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollaborator indicates an expected call of AddCollaborator.
func (mr *MockGithubRepoMockRecorder) AddCollaborator(ctx, repo, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollaborator", reflect.TypeOf((*MockGithubRepo)(nil).AddCollaborator), ctx, repo, username)
}

// CloneRepository mocks base method.
func (m *MockGithubRepo) CloneRepository(ctx context.Context, fullname, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneRepository", ctx, fullname, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneRepository indicates an expected call of CloneRepository.
func (mr *MockGithubRepoMockRecorder) CloneRepository(ctx, fullname, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneRepository", reflect.TypeOf((*MockGithubRepo)(nil).CloneRepository), ctx, fullname, id)
}

// CreateRepository mocks base method.
func (m *MockGithubRepo) CreateRepository(ctx context.Context, templateRepo, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, templateRepo, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockGithubRepoMockRecorder) CreateRepository(ctx, templateRepo, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockGithubRepo)(nil).CreateRepository), ctx, templateRepo, repo)
}

// GetErrorMsg mocks base method.
func (m *MockGithubRepo) GetErrorMsg(err error) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorMsg", err)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetErrorMsg indicates an expected call of GetErrorMsg.
func (mr *MockGithubRepoMockRecorder) GetErrorMsg(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorMsg", reflect.TypeOf((*MockGithubRepo)(nil).GetErrorMsg), err)
}

// GetTemplateRepository mocks base method.
func (m *MockGithubRepo) GetTemplateRepository(labid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateRepository", labid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTemplateRepository indicates an expected call of GetTemplateRepository.
func (mr *MockGithubRepoMockRecorder) GetTemplateRepository(labid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateRepository", reflect.TypeOf((*MockGithubRepo)(nil).GetTemplateRepository), labid)
}
